### ISSUE TITLE
Add `sort!` method for `LittleDict`

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaCollections/OrderedCollections.jl#116] opened 2024-06-26 18:13 UTC
My values are large data frames, and I don't want to have to copy them just to reorder the keys.

**Comment by fingolfin** [comment] 2024-11-24 21:48
Seems very reasonable! Alas, duplicate of issue #51.

**Closed by fingolfin** 2024-11-24 21:48 UTC

**Comment by fingolfin** [comment] 2024-11-24 22:01
(See also PR #136 for a fix)
